import Head from 'next/head'
import LandingPage from '../components/templates/LandingPage'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Book App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <LandingPage/>
    </div>
  )
}
