import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Book App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className='text-3xl text-orange-500'>
 Test
      </main>

      <footer className="font-bold">
Footer test
      </footer>
    </div>
  )
}
